- lib/main.dart
- lib/pages/feed/widgets/feed_item.dart
- lib/pages/more/settings_page.dart
This PR fixes the "System Darkmode" switch behaviour which appeared to be inverted.
> Settings systemDarkmode fix

- ios/Flutter/AppFrameworkInfo.plist
- ios/Flutter/Debug.xcconfig
- ios/Flutter/Release.xcconfig
- ios/Podfile
- ios/Podfile.lock
- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner.xcworkspace/contents.xcworkspacedata
- ios/Runner/Info.plist
- lib/main.dart
- lib/pages/calendar/calendar_detail_page.dart
- lib/pages/calendar/calendar_page.dart
- lib/pages/feed/feed_page.dart
- lib/pages/feed/rubnews/rubnews_details_page.dart
- lib/pages/feed/widgets/feed_item.dart
- lib/pages/guide/guide_page.dart
- lib/pages/home/home_page.dart
- lib/pages/home/widgets/bottom_nav_bar.dart
- lib/pages/mensa/mensa_page.dart
- lib/pages/more/more_page.dart
- lib/pages/more/settings_page.dart
This PR adjusts the UI to display the spacing properly regarding notches on several iPhone models.
> iOS adjustments

- ios/Runner.xcodeproj/project.pbxproj
- lib/main.dart
- lib/pages/mensa/widgets/expandable_restaurant.dart
- lib/utils/pages/mensa_utils.dart
This pull request fixes the following issues:
- #4 
- #15 
- Unnecessary logging of mensa categories
> Fix of several issues

- ios/Runner/Info.plist
- lib/core/settings.dart
- lib/main.dart
- lib/pages/calendar/calendar_page.dart
- lib/pages/feed/feed_page.dart
- lib/pages/feed/widgets/filter_popup.dart
- lib/pages/mensa/mensa_page.dart
- lib/pages/mensa/widgets/day_selection.dart
- lib/pages/more/more_page.dart
- lib/utils/widgets/campus_multiple_selection.dart
- lib/utils/widgets/campus_segmented_control.dart
This PR aims to adjust several UI parts:
- Mensa day selection adjusts to the rest of the page regarding the horizontal padding
- News and event items have less horizontal padding
- Events can now be mixed into the news feed or not by selecting that option in the filter popup
Moreover it adds the _Export compliance parameter_ for AppStore Connect.
> UI adjustments

- lib/pages/home/home_page.dart
- lib/pages/mensa/mensa_page.dart
This PR fixes issue https://github.com/astarub/campus_app/issues/16 and adjusts the refresh indicator color on the mensa page when the app is using the dark theme.
> Bottom nav menu fix

- pubspec.yaml
Adjusts the version patch number to 1.0.1 in order to publish the hotfix.
> Adjust version patch number

- lib/pages/mensa/dish_entity.dart
- lib/utils/pages/mensa_utils.dart
This should fix the issue #39 that if vegan food is preferred, vegetarian dishes are not shown.
> Change vegan meals to have the vegetarian label too

- assets/img/icons/message-square.svg
- assets/img/icons/siren.svg
- lib/pages/guide/guide_page.dart
- lib/pages/guide/widgets/leitwarte_button.dart
- lib/pages/more/more_page.dart
- lib/utils/constants.dart
- pubspec.yaml
This PR adds a button to call the _RUB Leitwarte_ in case of an emergency.
Additionally to that it adds a **feedback button** on the more page and **switches the mensa data source ip adress to the new AStA backend server**.
> Leitwarte call & backend server switch

- lib/main.dart
- lib/pages/home/home_page.dart
- lib/utils/pages/main_utils.dart
This PR adds the ability to direct the user to specific pages, based on the payload provided by the remote notification.
> Google Firebase Interaction Handling

- lib/pages/guide/guide_content.dart
1. Reformatted the file so it is actually readable and edible on a regular editor/screen
2. Changed Format of Phone Numbers
3. Added eCampus Entry
4. Made the URLs Text the same Text they Link to (was an inconsistency)
> Reformat and some Fixes for Guide Content

- lib/pages/calendar/entities/event_entity.dart
This PR fixes the bug where the currency for certain events was left out. 
Fixes #63
> Fix #63 - missing currency bug

- lib/pages/home/onboarding.dart
This PR fixes minor mistakes that were introduced with PR https://github.com/astarub/campus_app/pull/79.
> Onboarding hotfix

- lib/utils/pages/main_utils.dart
- pubspec.lock
- pubspec.yaml
This PR adjusts the positioning of the onboarding progress indicator on iOS.
During cross platform tests I noticed that the element was below the `FloatingActionButton` on iOS devices.
For further details, refer to the commit on the designated repository: https://github.com/C4s4r/flutter_onboarding/commit/9d74464318db64177e88f44a279fc88b9b542018
> Progress indicator positioning on iOS

- ios/Podfile.lock
- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner/Info.plist
This PR applies the Xcode changes that were introduced due to a different provisioning profile (added "Associated Domains" capability).
> Associated Domains in iOS Provisioning profile

- lib/pages/feed/widgets/feed_item.dart
- pubspec.lock
- pubspec.yaml
As https://github.com/astarub/campus_app/issues/37 is completed and can be deployed now, the version number is being upgraded from 1.0.3 to 1.1.0
If there are further bugs during alpha testing, they will be resolved within this PR.
> Update version to 1.1.0

- lib/pages/more/static_info_page.dart
This PR fixes another bug preventing users from scrolling in the in app view on the more page.
> Fix scrolling bug 

- lib/pages/wallet/mensa_balance_page.dart
- lib/pages/wallet/widgets/wallet.dart
- pubspec.lock
- pubspec.yaml
This PR fixes the bug where the mensa balance page stopped working after a tag was lost, resulting in the phone scanning without the card value being transceived. It also adds an error message for wrong file types uploaded as the Bogestra ticket.
> Wallet Bug Fixes

- lib/main.dart
- lib/pages/feed/widgets/filter_popup.dart
- lib/pages/home/home_page.dart
- lib/pages/home/page_navigator.dart
- lib/pages/home/widgets/bottom_nav_bar_item.dart
- lib/pages/home/widgets/side_nav_bar.dart
- lib/pages/mensa/widgets/day_selection.dart
- lib/pages/moodle/moodle_page.dart
- lib/pages/wallet/widgets/stacked_card_carousel.dart
- lib/utils/widgets/campus_switch.dart
- lib/utils/widgets/decision_popup.dart
- lib/utils/widgets/popup_sheet.dart
Constructors should be const its faster
unneded imports and default settings removes
local vars final
> Some small fixes

- lib/pages/mensa/mensa_page.dart
is there any specific reason why there is no await used with this async call?
> async await

- android/app/src/main/kotlin/com/example/campus_app/PopupActivity.kt
- android/build.gradle
- lib/pages/calendar/calendar_repository.dart
- lib/pages/feed/feed_page.dart
- lib/pages/rubsignin/widgets/signin_form.dart
- pubspec.yaml
This PR implements an Android specific functionality and fixes a series of typos, bugs and deprecated attributes. 
The Android specific functionality, is an extenstion of the mensa card balance page but with the little extra that the app doesn't have to be running, as a popup window is spawned once a campus card is detected.
> 🛰️ Update 2.0.1 

- lib/pages/more/in_app_web_view_page.dart
- lib/pages/wallet/mensa_balance_page.dart
- lib/utils/pages/mensa_utils.dart
Trailing Comma, ignore escapes
> small syntax fix

- ios/Podfile.lock
- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- lib/pages/wallet/mensa_balance_page.dart
- pubspec.lock
- pubspec.yaml
This PR updates the native splash and flutter_ncf_kit dependencies. 
The later fixes an issue that's caused by an IllegalStateException.
> Update dependency & fix crashing due to nfc error

- ios/Flutter/AppFrameworkInfo.plist
- ios/Podfile.lock
- ios/Runner.xcodeproj/project.pbxproj
This PR updates the iOS configuration to suit the new deployment target of iOS 13 and later.
> Update iOS deployment target

- docs/wiki/Backend.md
- lib/core/backend/backend_repository.dart
- lib/core/backend/entities/study_course_entity.dart
- lib/main.dart
- lib/pages/feed/feed_page.dart
- lib/pages/feed/news/news_details_page.dart
- lib/pages/feed/widgets/feed_item.dart
- lib/pages/feed/widgets/video_player.dart
- lib/pages/mensa/mensa_page.dart
- pubspec.lock
- pubspec.yaml
This PR fixes the bug, where the initial Settings object is populated with an immutable list.
Study courses now have a ``faculty`` attribute too.
> 2.1.0 Update Bug Fixes 

- lib/pages/feed/widgets/feed_item.dart
- lib/utils/pages/feed_utils.dart
This PR fixes a bug, where refereshing the feed did not remove outdated feed items, which was only performed on restart.
> Version 2.1.0 - Fix Feed Bug

- ios/Podfile.lock
- pubspec.yaml
This PR updates the iOS pods for the updated packages in #150 .
> Version 2.2.1 Update - Update iOS pods

- analysis_options.yaml
- ios/Podfile.lock
- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- lib/main.dart
- lib/pages/calendar/calendar_detail_page.dart
- lib/pages/calendar/widgets/event_widget.dart
- lib/pages/feed/news/news_details_page.dart
- lib/pages/feed/widgets/feed_item.dart
- lib/pages/home/widgets/bottom_nav_bar_item.dart
- lib/pages/mensa/widgets/day_selection.dart
- lib/utils/pages/mensa_utils.dart
- lib/utils/pages/wallet_utils.dart
- pubspec.lock
- pubspec.yaml
Dismiss feed_details_page and event_details_page by swiping instead of navigating with the bottom navigation bar.
> Feed & Event swipe

- ios/Podfile.lock
- lib/pages/calendar/calendar_detail_page.dart
- lib/pages/calendar/calendar_page.dart
- lib/pages/calendar/entities/event_entity.dart
- lib/pages/calendar/widgets/event_widget.dart
- lib/pages/feed/news/news_entity.dart
- lib/pages/feed/widgets/feed_item.dart
- lib/pages/more/in_app_web_view_page.dart
- lib/utils/pages/calendar_utils.dart
- lib/utils/pages/feed_utils.dart
- pubspec.lock
- pubspec.yaml
This PR adds the functionality to mark certain feed & calendar items as pinned, resulting in the marked entries to be displayed at the top of each page.
Furthermore the flutter_nfc_kit package was set back to the original repository.
> Pinnable feed & event items

- ios/Podfile.lock
- lib/pages/feed/news/news_datasource.dart
- lib/pages/feed/news/news_entity.dart
- lib/pages/feed/widgets/feed_item.dart
- lib/pages/wallet/ticket/ticket_usecases.dart
- lib/pages/wallet/ticket_fullscreen.dart
- lib/utils/pages/feed_utils.dart
- pubspec.lock
- pubspec.yaml
- windows/flutter/generated_plugin_registrant.cc
- windows/flutter/generated_plugins.cmake
As in #182 described, the feed is currently not working properly as the RUB has changed the structure of their newsfeed articles that cannot be comprehended by the current image extraction system.
This PR mitigates that issue by adjusting the image extraction system to suit the most recent HTML structure of the newsfeed. 
Additionally this PR updates various packages.
> Fix the feed & package updates

- lib/utils/pages/main_utils.dart
- pubspec.lock
- pubspec.yaml
- windows/flutter/generated_plugin_registrant.cc
- windows/flutter/generated_plugins.cmake
This PR replaces the `uni_links` package that is not actively worked on, with the more recent `app_links` package.
> Update universal links package
